server:
  port: 80
spring:
  freemarker:
    template-loader-path:
    - classpath:/template
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    request-context-attribute: request
    suffix: .htm