
package liyu.test.wscli;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrganizationImplService", targetNamespace = "http://aozhe.com/", wsdlLocation = "http://192.168.145.1:21110/Portal/WebServices/Organization?wsdl")
public class OrganizationImplService
    extends Service
{

    private final static URL ORGANIZATIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORGANIZATIONIMPLSERVICE_EXCEPTION;
    private final static QName ORGANIZATIONIMPLSERVICE_QNAME = new QName("http://aozhe.com/", "OrganizationImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.145.1:21110/Portal/WebServices/Organization?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORGANIZATIONIMPLSERVICE_WSDL_LOCATION = url;
        ORGANIZATIONIMPLSERVICE_EXCEPTION = e;
    }

    public OrganizationImplService() {
        super(__getWsdlLocation(), ORGANIZATIONIMPLSERVICE_QNAME);
    }

    public OrganizationImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORGANIZATIONIMPLSERVICE_QNAME, features);
    }

    public OrganizationImplService(URL wsdlLocation) {
        super(wsdlLocation, ORGANIZATIONIMPLSERVICE_QNAME);
    }

    public OrganizationImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORGANIZATIONIMPLSERVICE_QNAME, features);
    }

    public OrganizationImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrganizationImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrganizationImpl
     */
    @WebEndpoint(name = "OrganizationImplPort")
    public OrganizationImpl getOrganizationImplPort() {
        return super.getPort(new QName("http://aozhe.com/", "OrganizationImplPort"), OrganizationImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrganizationImpl
     */
    @WebEndpoint(name = "OrganizationImplPort")
    public OrganizationImpl getOrganizationImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://aozhe.com/", "OrganizationImplPort"), OrganizationImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORGANIZATIONIMPLSERVICE_EXCEPTION!= null) {
            throw ORGANIZATIONIMPLSERVICE_EXCEPTION;
        }
        return ORGANIZATIONIMPLSERVICE_WSDL_LOCATION;
    }

}
