
package liyu.test.wscli;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrganizationImpl", targetNamespace = "http://aozhe.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrganizationImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.GetNameResponse")
    @Action(input = "http://aozhe.com/OrganizationImpl/getNameRequest", output = "http://aozhe.com/OrganizationImpl/getNameResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://aozhe.com/OrganizationImpl/getName/Fault/Exception")
    })
    public String getName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getParent", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.GetParent")
    @ResponseWrapper(localName = "getParentResponse", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.GetParentResponse")
    @Action(input = "http://aozhe.com/OrganizationImpl/getParentRequest", output = "http://aozhe.com/OrganizationImpl/getParentResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://aozhe.com/OrganizationImpl/getParent/Fault/Exception")
    })
    public String getParent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isAncestor", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.IsAncestor")
    @ResponseWrapper(localName = "isAncestorResponse", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.IsAncestorResponse")
    @Action(input = "http://aozhe.com/OrganizationImpl/isAncestorRequest", output = "http://aozhe.com/OrganizationImpl/isAncestorResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://aozhe.com/OrganizationImpl/isAncestor/Fault/Exception")
    })
    public boolean isAncestor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFullName", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.GetFullName")
    @ResponseWrapper(localName = "getFullNameResponse", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.GetFullNameResponse")
    @Action(input = "http://aozhe.com/OrganizationImpl/getFullNameRequest", output = "http://aozhe.com/OrganizationImpl/getFullNameResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://aozhe.com/OrganizationImpl/getFullName/Fault/Exception")
    })
    public String getFullName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns liyu.test.wscli.WebServiceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.UpdateUserResponse")
    @Action(input = "http://aozhe.com/OrganizationImpl/updateUserRequest", output = "http://aozhe.com/OrganizationImpl/updateUserResponse")
    public WebServiceResult updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getManager", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.GetManager")
    @ResponseWrapper(localName = "getManagerResponse", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.GetManagerResponse")
    @Action(input = "http://aozhe.com/OrganizationImpl/getManagerRequest", output = "http://aozhe.com/OrganizationImpl/getManagerResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://aozhe.com/OrganizationImpl/getManager/Fault/Exception")
    })
    public String getManager(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://aozhe.com/", className = "liyu.test.wscli.AddUserResponse")
    @Action(input = "http://aozhe.com/OrganizationImpl/addUserRequest", output = "http://aozhe.com/OrganizationImpl/addUserResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://aozhe.com/OrganizationImpl/addUser/Fault/Exception")
    })
    public String addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1)
        throws Exception_Exception
    ;

}
