package com.iot.ssm.po;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbg.generated Mon Jan 08 15:04:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.name
     *
     * @mbg.generated Mon Jan 08 15:04:38 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.login_name
     *
     * @mbg.generated Mon Jan 08 15:04:38 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.author
     *
     * @mbg.generated Mon Jan 08 15:04:38 CST 2018
     */
    private Integer author;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbg.generated Mon Jan 08 15:04:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbg.generated Mon Jan 08 15:04:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.name
     *
     * @return the value of blog.name
     *
     * @mbg.generated Mon Jan 08 15:04:38 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.name
     *
     * @param name the value for blog.name
     *
     * @mbg.generated Mon Jan 08 15:04:38 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.login_name
     *
     * @return the value of blog.login_name
     *
     * @mbg.generated Mon Jan 08 15:04:38 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.login_name
     *
     * @param loginName the value for blog.login_name
     *
     * @mbg.generated Mon Jan 08 15:04:38 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.author
     *
     * @return the value of blog.author
     *
     * @mbg.generated Mon Jan 08 15:04:38 CST 2018
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.author
     *
     * @param author the value for blog.author
     *
     * @mbg.generated Mon Jan 08 15:04:38 CST 2018
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }
}